name: maintenance-task-ui

type: ruby

up:
  - ruby: 2.7.1
  - bundler

commands:
  test:
    syntax:
      argument: file
      optional: args...
    run:  |
      if [[ $# -eq 0 ]]; then
        bundle exec rake test
      else
        bundle exec ruby -I test "$@"
      fi
